name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Print working directory
      run: pwd
    - name: List files in root
      run: ls -la
    - name: List files in app directory
      run: ls -la app
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x app/gradlew
    - name: Change directory to app
      run: cd app
    - name: Build with Gradle
      run: ./gradlew build
